# Name of this GitHub Actions workflow.
name: Semgrep

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]
    paths:
    - .github/workflows/semgrep.yml
  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '20 17 * * *' # Sets Semgrep to scan every day at 17:20 UTC.
    # It is recommended to change the schedule to a random time.

jobs:
  buildGradleLockFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          export GRADLE_USER_HOME=`pwd`/.gradle
          echo "dependencyLocking { lockAllConfigurations() }" >> build.gradle
          ./gradlew assemble
          ./gradlew check
          gradle dependencies --write-locks
          gradle clean compileJava
      - name: Build Dependency Lock File
        run: gradle dependencies --write-locks
      - name: Upload Gradle Lock File
        uses: actions/upload-artifact@v3
        with:
          name: gradlelockfile
          path: /Users/michael.bali/project/gradle-test/settings-gradle.lockfile

  semgrep:
    needs: buildGradleLockFile
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: gradlelockfile
      - run: semgrep ci